version: "3.9"

services:
  django:
    build: ./backend
    container_name: django_app
    expose:
      - "8000"
    environment:
      DJANGO_SECRET_KEY: supersecretkey123
      FRONTEND_URL: http://localhost
      ALLOWED_HOSTS: "*"
      DEBUG: "True"
    restart: always

  nextjs:
    build: ./frontend
    container_name: nextjs_app
    expose:
      - "3000"
    depends_on:
      - django
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - nextjs
    restart: always
